# Generated by Django 5.0.6 on 2024-09-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_name", models.CharField(max_length=50)),
                ("fee", models.IntegerField()),
                ("duration", models.CharField(max_length=50)),
                ("stardate", models.DateTimeField()),
                ("trainer_name", models.CharField(max_length=50)),
                ("trainer_exp", models.CharField(max_length=10)),
                ("training_mode", models.CharField(max_length=15)),
            ],
        ),
    ]
