# Generated by Django 5.0.6 on 2024-09-08 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Instituteapp", "0003_contact"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
