# Generated by Django 5.0.6 on 2024-09-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Instituteapp", "0004_delete_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback", models.CharField(max_length=100)),
            ],
        ),
    ]
