# Generated by Django 5.1.1 on 2024-09-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Instituteapp", "0005_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("StudentName", models.CharField(max_length=50)),
                ("Emailid", models.EmailField(max_length=254)),
                ("Contactno", models.BigIntegerField()),
                ("CourseName", models.CharField(max_length=30)),
                ("CourseFee", models.IntegerField()),
                ("CourseDuration", models.CharField(max_length=10)),
                ("StartDate", models.CharField(max_length=50)),
                ("trainer_name", models.CharField(max_length=50)),
                ("trainingmode", models.CharField(max_length=10)),
            ],
        ),
    ]
