# Generated by Django 5.1.1 on 2024-09-12 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Instituteapp", "0008_enrollstudent"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
