# Generated by Django 5.1.1 on 2024-09-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Instituteapp", "0009_delete_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=20)),
                ("Email", models.EmailField(max_length=254)),
                ("Mobileno", models.BigIntegerField()),
                ("Course", models.CharField(max_length=10)),
                ("location", models.CharField(max_length=100)),
            ],
        ),
    ]
